### ISSUE TITLE
Example returns bad request error

### ISSUE THREAD

**Issue by thmsdelange** [cercide/fastapi-xml#1]
Hi,

I need to develop a simple xml api and wanted to make use of your package but I'm having some issues getting the example to work. Opening the docs and executing the example request on the /echo post endpoint at "Try it out" returns a bad request error with response body:

```
{
  "detail": "Unknown property echo:message"
}
```

Can you guide me to a solution?

Thanks in advance

**Comment by cercide** [comment]
Please note the this project is still at alpha stage. There has been significant changes in pydantic recently. The current version (1.10.2) seems to be not compatible. pydantic 1.9.2 will do the trick

```
pip3 uninstall pydantic
pip3 install pydantic==1.9.2
```

**Comment by cercide** [comment]
`pydantic 1.10.*` supported by since `1.0.0b1`.
closed.
