### ISSUE TITLE
Is it possible to set default values for dataClasses in fastapi-xml?

### ISSUE THREAD

**Issue by rsoika** [cercide/fastapi-xml#10]
Currently my metadata seems to be ignored by the swager UI

example class:

```python
@dataclass
class PromptData:
    model_id: str = field()

    prompt: str = field(
        metadata={
            "example": "What is the Imixs-Workflow engine?",
            "name": "prompt", 
            "type": "Element"
        }
    )    

    output: str = field(
        metadata={
            "name": "output", 
            "type": "Element"
        }
    )   
```

Post Method

```python
@app.post("/prompt", response_model=datamodel.PromptData, tags=["Imixs-AI"])
def prompt(data: datamodel.PromptData = XmlBody()) -> datamodel.PromptData:
  ...
```

Results in 

![grafik](https://github.com/cercide/fastapi-xml/assets/1339124/e9bc0acb-9308-48bf-aa62-a1d4444ee041)

Is there a way to set default data somehow?

**Comment by cercide** [comment]
Since the original json openapi fails to represent the example value, it seems that pydantic discards/ignores it somehow.
Newertheless, when using example**s** it seems to work.

```
"examples": ["What is the Imixs-Workflow engine?"],
```

Please let me know If this solves your issue.

**Comment by rsoika** [comment]
Yes, this works, packaging the example text int [ ] works!

Thanks!

You just should update your examples.
