### ISSUE TITLE
CDATA element in dataclass?

### ISSUE THREAD

**Issue by rsoika** [cercide/fastapi-xml#11]
Is it possible to define a dataclass that represents a string wrapped in CDATA 

like:

```xml
<PromptData>
	<prompt><![CDATA[
.....
]]></prompt>
</PromptData> 
```

**Comment by cercide** [comment]
I am not sure about that. Have you figured out, how to do it with xsdata alone?

By myself, i did not find any reference within the xsdata documentation. Please keep me updated if you figure this out.

**Comment by rsoika** [comment]
Hi @cercide , no I did not - [xsdata](https://xsdata.readthedocs.io/en/v20.4.2/dataclasses.html) did not mention CDATA. 
I found [this discussion](https://stackoverflow.com/questions/76118436/how-to-create-cdata-sections-with-the-xsdata-library) but I do not now how to adapt this (I am new to python)

**Comment by cercide** [comment]
Upon further research, unfortunately, there's no easy solution. Let's start with the basics.

**What is CDATA?**
In [this post](https://stackoverflow.com/questions/54205846/how-to-define-cdata-attribute-in-swagger-2-0), Helen succinctly explains:
"CDATA is not part of the XML logical structure; it's simply a way to indicate text containing special characters to prevent such text from being interpreted as XML markup."

**How does fastapi-xml work?**
This library is straightforward:
```
Request -> Decoder -> [your code] -> Encoder -> Response
```
Or, in library terms:
```
FastAPI -> xsdata -> [your code] -> xsdata -> FastAPI
```

**How to use CDATA with fastapi-xml?**
You don't.
xsdata does not support CDATA. OpenAPI does not support CDATA. Therefore, fastapi-xml does not support CDATA.

**How do I implement CDATA support?**
Consider using a [Custom Route](https://fastapi.tiangolo.com/how-to/custom-request-and-route/) along with [lxml](https://stackoverflow.com/questions/76118436/how-to-create-cdata-sections-with-the-xsdata-library).
